### ISSUE TITLE
User setting persistence issue

### ISSUE THREAD

**Issue by tmedwards** [ChapelR/volume-slider-for-sugarcube2#2]
Apparently there's a user setting persistence issue in the current version.

**SEE:** [Chapels volume control (from: r/twinegames)](https://www.reddit.com/r/twinegames/comments/pnacww/chapels_volume_control/?utm_source=share&utm_medium=ios_app&utm_name=iossmf).

**Comment by ChapelR** [comment]
Thanks, I'll fix it when I have time.

**Comment by SjoerdHekking** [comment]
Hey there, any news on this issue? I am facing the same problems.
